# Generated by Django 3.2.7 on 2021-09-12 04:04

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('mailreporter', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactperson',
            name='message',
            field=tinymce.models.HTMLField(),
        ),
    ]
