# Generated by Django 3.2.7 on 2021-09-12 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailreporter', '0002_alter_contactperson_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactperson',
            name='message',
            field=models.CharField(max_length=255),
        ),
    ]
