# Generated by Django 3.2.7 on 2021-09-12 05:08

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('mailreporter', '0003_alter_contactperson_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactperson',
            name='message',
            field=tinymce.models.HTMLField(),
        ),
    ]
