# Generated by Django 4.2.4 on 2023-08-26 21:22

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SpamMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('time', models.CharField(blank=True, max_length=35, null=True)),
                ('email', models.CharField(default='example@example.com', max_length=255)),
                ('domain', models.CharField(default='example.com', max_length=255)),
                ('emlfile', models.FileField(blank=True, default='', null=True, upload_to='eml/%Y/%m/%d/')),
                ('state', models.CharField(choices=[('finished', 'finished'), ('queue', 'queue'), ('processing', 'processing'), ('todo', 'todo')], default='todo', max_length=16)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='SpamIp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(default='0.0.0.0', max_length=255)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spammers.spammessage', verbose_name='SpamEmail')),
            ],
        ),
    ]
