# Generated by Django 3.2.6 on 2021-08-21 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spammers', '0002_auto_20210808_0242'),
    ]

    operations = [
        migrations.AddField(
            model_name='spammessage',
            name='emilfile',
            field=models.FileField(blank=True, default='', null=True, upload_to='eml/%Y/%m/%d'),
        ),
    ]
