# Generated by Django 3.2.6 on 2021-08-21 03:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spammers', '0003_spammessage_emilfile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='spammessage',
            old_name='emilfile',
            new_name='emlfile',
        ),
    ]
