# Generated by Django 3.2.6 on 2021-08-23 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spammers', '0006_alter_spamip_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spammessage',
            name='time',
            field=models.CharField(blank=True, max_length=35, null=True),
        ),
    ]
