# Generated by Django 3.2.6 on 2021-08-23 03:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spammers', '0007_alter_spammessage_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spamip',
            name='email',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spammers.spammessage', verbose_name='SpamEmail'),
        ),
    ]
