# Generated by Django 3.2.6 on 2021-08-23 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spammers', '0008_alter_spamip_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spamip',
            name='ip',
            field=models.CharField(default='0.0.0.0', max_length=255),
        ),
        migrations.AlterField(
            model_name='spammessage',
            name='domain',
            field=models.CharField(default='example.com', max_length=255),
        ),
        migrations.AlterField(
            model_name='spammessage',
            name='email',
            field=models.CharField(default='example@example.com', max_length=255),
        ),
    ]
