# Generated by Django 3.2.6 on 2021-08-29 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spammers', '0009_auto_20210823_0103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spammessage',
            name='state',
            field=models.CharField(choices=[('finished', 'finished'), ('queue', 'queue'), ('processing', 'processing'), ('todo', 'todo')], default='todo', max_length=16),
        ),
    ]
