# Generated by Django 3.2.7 on 2021-09-12 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spammers', '0010_alter_spammessage_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spammessage',
            name='emlfile',
            field=models.FileField(blank=True, default='', null=True, upload_to='eml/%Y/%m/%d/'),
        ),
    ]
